package ServerApp;


/**
* ServerApp/ServerHelpPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Tuesday, August 27, 2019 1:30:42 o'clock PM EDT
*/

public abstract class ServerHelpPOA extends org.omg.PortableServer.Servant
 implements ServerApp.ServerHelpOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("upload", new java.lang.Integer (1));
    _methods.put ("updateDatabase", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerApp/ServerHelp/login
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.login (username, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ServerApp/ServerHelp/upload
       {
         String username = in.read_string ();
         String filename = in.read_string ();
         String clientOpt = in.read_string ();
         String $result = null;
         $result = this.upload (username, filename, clientOpt);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //string updateProperties(in string username, in string address, in long port);
       case 2:  // ServerApp/ServerHelp/updateDatabase
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.updateDatabase (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ServerApp/ServerHelp/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerApp/ServerHelp:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerHelp _this() 
  {
    return ServerHelpHelper.narrow(
    super._this_object());
  }

  public ServerHelp _this(org.omg.CORBA.ORB orb) 
  {
    return ServerHelpHelper.narrow(
    super._this_object(orb));
  }


} // class ServerHelpPOA
