package ServerApp;


/**
* ServerApp/ServerHelpOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Tuesday, August 27, 2019 1:30:42 o'clock PM EDT
*/

public interface ServerHelpOperations 
{
  String login (String username, String password);
  String upload (String username, String filename, String clientOpt);

  //string updateProperties(in string username, in string address, in long port);
  String updateDatabase (String username);
  void shutdown ();
} // interface ServerHelpOperations
