package ServerApp;

/**
* ServerApp/ServerHelpHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Tuesday, August 27, 2019 1:30:42 o'clock PM EDT
*/

public final class ServerHelpHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerApp.ServerHelp value = null;

  public ServerHelpHolder ()
  {
  }

  public ServerHelpHolder (ServerApp.ServerHelp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerApp.ServerHelpHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerApp.ServerHelpHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerApp.ServerHelpHelper.type ();
  }

}
