package ServerApp;


/**
* ServerApp/ServerHelp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Tuesday, August 27, 2019 1:30:42 o'clock PM EDT
*/

public interface ServerHelp extends ServerHelpOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerHelp
